[icons]
# font awesome
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
Thunderbird = ""
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "✈️"
"Org.gnome.Nautilus" = "Nautilus"
"org.wezfurlong.wezterm" = "🎮"
"org.kde.okular" = "📖"
"org.telegram.desktop" = "✈️"
"org.jetbrains.rider" = "Rider"
"firefox" = "🦊" 
"brave" = "🦁"
"brave-browser" = "🦁"
"google-chrome" = "🦖"
"Bytedance-feishu" = "📘"

[general]
separator = ""

[options]
no-names = true
remove-duplicates = true
