[icons]
# font awesome
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
Thunderbird = ""
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"
"org.wezfurlong.wezterm" = "Wezterm"
"org.kde.okular" = "📖"
"org.telegram.desktop" = "Telegram"
"org.jetbrains.rider" = "Rider"
"firefox" = "🦊" 

[general]
separator = ""

[options]
no-names = true
remove-duplicates = true
