version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "America/New_York"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5

  - package-ecosystem: nix
    directory: "/"
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "America/New_York"
    groups:
      flake-inputs:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
